### ISSUE TITLE
Per-project settings are ignored

### ISSUE THREAD

**Issue by cilefen** [benmatselby/sublime-phpcs#110]
Hi, 

Many thanks for developing and maintaining this plugin.

I am trying to get the per-project settings configured but they seem to be ignored entirely. With the configuration below, the default PEAR standard is run, every time. As far as I can tell, the default phpcs plugin settings are working.

This is ST2 and 6.3.5 of this plugin.

Do you know at a glance if anything is wrong here?

```
{
	"folders":
	[
		{
			"path": "./"
		}
	],
	"settings":
    {
        "tab_size": 2,
        "translate_tabs_to_spaces": true,
        "phpcs": 
        {
            "phpcs_additional_args": {
                "--standard": "Drupal"
            },
            "show_debug": true,
            "extensions_to_execute": ["php", "module", "inc", "install", "test"],
            "phpmd_run": true,
            "phpmd_additional_args": {
                "codesize,design,unusedcode": ""
            }
        }
    }
}
```

**Comment by benmatselby** [comment]
Closing as Sublime Text 3 has been out a while, and this has been open for over two years. I'm now using phpStorm, so support on this is limited, so if it works in ST3, I'm happy with that.
