### ISSUE TITLE
[WinError 2] The system cannot find the file specified

### ISSUE THREAD

**Issue by blueliquiddesigns** [benmatselby/sublime-phpcs#123]
Hi,

I've got everything installed correctly on Windows but saw the error '[WinError 2] The system cannot find the file specified' was being generated in the console when saving.

I ran the command manually in the command prompt and found that because my path to the file had spaces it wasn't working correctly. However, if I wrapped the path in quotes it correctly ran. 

eg.
This throws errors: phpcs --report=checkstyle --standard=PSR2 -n  C:\My Path\To\File\index.php
This works correctly: phpcs --report=checkstyle --standard=PSR2 -n  "C:\My Path\To\File\index.php"

**Comment by benmatselby** [comment]
Which version of Sublime Text are you using please? I'm pretty sure there is another issue here, as since most windows paths have spaces in I would imagine this would be more prevalent. Can you please paste the output from the console and your config please.

**Comment by blueliquiddesigns** [comment]
Hi Ben,

I'm using Sublime Text 3.

Sure. There console is:

`
Writing file /G/BLD/4) BLD/12) FTP/domains/clients.blueliquiddesigns.com.au/public_html/gfpdf3/gf1_7/wordpress/wp-content/plugins/gravity-forms-pdf-extended/tests/test-entry-detail.php with encoding UTF-8 (atomic)
[Phpcs] phpcs --report=checkstyle --standard=PSR2 -n G:\BLD\4) BLD\12) FTP\domains\clients.blueliquiddesigns.com.au\public_html\gfpdf3\gf1_7\wordpress\wp-content\plugins\gravity-forms-pdf-extended\tests\test-entry-detail.php
[Phpcs] phpcs --report=checkstyle --standard=PSR2 -n G:\BLD\4) BLD\12) FTP\domains\clients.blueliquiddesigns.com.au\public_html\gfpdf3\gf1_7\wordpress\wp-content\plugins\gravity-forms-pdf-extended\tests\test-entry-detail.php
[Phpcs] cwd: C:\Users\Jake Jackson
Exception in thread Thread-13:
Traceback (most recent call last):
  File "./subprocess.py", line 1112, in _execute_child
FileNotFoundError: [WinError 2] The system cannot find the file specified

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./threading.py", line 901, in _bootstrap_inner
  File "./threading.py", line 858, in run
  File "phpcs in C:\Users\Jake Jackson\AppData\Roaming\Sublime Text 3\Installed Packages\Phpcs.sublime-package", line 433, in run
  File "phpcs in C:\Users\Jake Jackson\AppData\Roaming\Sublime Text 3\Installed Packages\Phpcs.sublime-package", line 139, in get_errors
  File "phpcs in C:\Users\Jake Jackson\AppData\Roaming\Sublime Text 3\Installed Packages\Phpcs.sublime-package", line 215, in execute
  File "phpcs in C:\Users\Jake Jackson\AppData\Roaming\Sublime Text 3\Installed Packages\Phpcs.sublime-package", line 218, in parse_report
  File "phpcs in C:\Users\Jake Jackson\AppData\Roaming\Sublime Text 3\Installed Packages\Phpcs.sublime-package", line 169, in shell_out
  File "./subprocess.py", line 824, in __init__
  File "./subprocess.py", line 1118, in _execute_child
FileNotFoundError: [WinError 2] The system cannot find the file specified
`

If I paste the phpcs command into the command prompt it gives me the error `Error: The file "G:\BLD\R)" does not exist.

**Comment by benmatselby** [comment]
And what's your config file please?

**Comment by blueliquiddesigns** [comment]
Other than the standard config I just enabled debugging to see what the issue was and turned off the linter:


	"show_debug": true,

    // Are we going to run php -l over the file?
    "phpcs_linter_run": false,

    // Execute the linter on file save
    "phpcs_linter_command_on_save": false,

**Comment by benmatselby** [comment]
Please have a look at this bit of the README.md:

https://github.com/benmatselby/sublime-phpcs#what-do-i-do-when-i-get-oserror-error-2-no-such-file-or-directory

I think you will need to fully specify the PATH of phpcs

**Comment by blueliquiddesigns** [comment]
Hi Ben,

Thanks for all your help with this. To get it working I had to link directly to the .bat files I set up to make phpcs run globally through the command prompt. The following fixed the issue:

    "phpcs_executable_path": "C:\\php-5.6.2\\phpcs.bat",

    "php_cs_fixer_executable_path": "C:\\php-5.6.2\\php-cs-fixer.bat",

    "phpmd_executable_path": "C:\\php-5.6.2\\phpmd.bat",

I miss Ubuntu! Windows really isn't friendly with the command prompt.

**Comment by nikitasahai** [comment]
Hello,
I searched a lot of topics and finally found the answer here. Thankyou very much. It worked at last :)

**Comment by shivapoudel** [comment]
@jakejackson1 where to put this code in `.sublimelinterrc` or in otherr place.
