### ISSUE TITLE
Is there a way to run phpcbf on a file?

### ISSUE THREAD

**Issue by louisl** [benmatselby/sublime-phpcs#127]
I cant find an option or way to configure running phpcbf on a file.

Regards

Louis

**Comment by benmatselby** [comment]
Hi there @louisl 

At the moment, no, but adding it wouldn't be too hard to be honest. I'm a little strapped for time at the moment, but would take a PR. If not I'll get to it at some point. I've tagged this as an enhancement

**Comment by benmatselby** [comment]
@louisl Yes there is now, 6.6.0 has just been released.
