### ISSUE TITLE
Reported parse error on correct PHP 5.5 syntax.

### ISSUE THREAD

**Issue by Pictor13** [benmatselby/sublime-phpcs#128]
Using the Sublime extension I'm getting one error notification

> PHP Parse error: parse error, expecting '"identifier (T_STRING)"' or '"variable (T_VARIABLE)"' or ''{" or ''$" in <file>

in correspondence of lines using the new (PHP 5.5) keyword **"::class"**, in code like

    return Classname::class;

that is a correct syntax for getting the fully qualified class-name.

Using PHPCS directly on my files from the shell, with

    phpcs --standard=PSR2 <file_path>

is working well, and I get no reports.

It seems that a different version of PHPCS is being used, or that its parameters are different.

That's making many of my (correct) files to be recognised as incorrect.

How could I solve?

**Comment by benmatselby** [comment]
Hi @Pictor13 

Can you give me your config please, and also the output from the console when running the commands. You will need to set ```"show_debug": true``` in your config

This will help us understand what is being run

**Comment by Pictor13** [comment]
Sure!

My configuration is the default one (tell me if you want me to paste it anyway); I didn't edit it. And my User settings has just the 'debug' flag enabled, for now.

This is the console report:

>
[Phpcs] Project files:
[Phpcs]  Current: None
[Phpcs]  Last Known: None
[Phpcs] No project file defined, therefore skipping reload
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 240, in on_pre_save
    callback.on_pre_save(v)
  File "trailing_spaces in /Users/pictor13/Library/Application Support/Sublime Text 3/Installed Packages/TrailingSpaces.sublime-package", line 424, in on_pre_save
  File "trailing_spaces in /Users/pictor13/Library/Application Support/Sublime Text 3/Installed Packages/TrailingSpaces.sublime-package", line 440, in freeze_last_version
  File "./codecs.py", line 885, in open
FileNotFoundError: [Errno 2] No such file or directory: '/Users/pictor13/test/classkeyword.php'
[Phpcs] php -l -d display_errors=On /Users/pictor13/test/classkeyword.php
[Phpcs] php -l -d display_errors=On /Users/pictor13/test/classkeyword.php
[Phpcs] cwd: /Users/pictor13
[Phpcs] PHP Parse error:  parse error, expecting `"identifier (T_STRING)"' or `"variable (T_VARIABLE)"' or `'{'' or `'$'' in /Users/pictor13/test/classkeyword.php on line 9
>
Parse error: parse error, expecting `"identifier (T_STRING)"' or `"variable (T_VARIABLE)"' or `'{'' or `'$'' in /Users/pictor13/test/classkeyword.php on line 9
Errors parsing /Users/pictor13/test/classkeyword.php
>
[Phpcs] phpcs --report=checkstyle -n --standard=PSR2 /Users/pictor13/test/classkeyword.php
[Phpcs] phpcs --report=checkstyle -n --standard=PSR2 /Users/pictor13/test/classkeyword.php
[Phpcs] cwd: /Users/pictor13
[Phpcs] <?xml version="1.0" encoding="UTF-8"?>
<checkstyle version="2.3.0">
</checkstyle>
>
[Phpcs] Linter found 1 errors
[Phpcs] Sniffer found 0 errors

**Comment by benmatselby** [comment]
On your terminal can you please do:

```
$ which php
$ which phpcs
```

And report back. I wonder if you are running native php from the mac within Sublime and on the terminal you are using brew or some other versioned php?

I think you may want to look at:

```
"phpcs_php_path": "/usr/local/opt/php56/bin/php",
```

Which is my php path, using 5.6

**Comment by Pictor13** [comment]
Mmmh I guess we maybe found the issue.

My "phpcs_php_path" is not set, so I'm getting it from OSX.
Actually the most updated PHP version (that I'm writing for) is on my development-virtual-machine, while my Mac still have PHP 5.4.
And obviously Sublime is relying on the local version of PHP (not the one from the development environment), so it finds the new "::class" keyword as invalid cause it doesn't have it into its used language version.

I will try to update my local PHP version and I will report back.
Thanks!

**Comment by benmatselby** [comment]
@Pictor13 Great, let me know if I can close this issue, ta

**Comment by benmatselby** [comment]
Hi @Pictor13 - how you getting on, can this be closed?

**Comment by Pictor13** [comment]
Yes, sorry for the delay. I just upgrade yesterday and the issue is fixed!

Thank you for you assistance, and for the plugin!

**Comment by benmatselby** [comment]
No worries, glad it is resolved.
