### ISSUE TITLE
Add php.tools' fmt.phar support

### ISSUE THREAD

**Issue by dericofilho** [benmatselby/sublime-phpcs#130]
I am an user of phpcs and author of php.tools. I should like to know if you would be willing to accept a PR to add support for php.tool's fmt.phar. If so, I will do it.

**Comment by benmatselby** [comment]
Hi there @dericofilho I see you already have a sublime plugin, would it be a replica of that inside of sublime-phpcs?

**Comment by dericofilho** [comment]
@benmatselby effectively, I am proposing to merge sublime-phpfmt into sublime-phpcs. It would take few releases to complete.

**Comment by benmatselby** [comment]
@dericofilho Aye, if it fits in so everything is optional, like the scheck integration, that is fine.

**Comment by dericofilho** [comment]
Closing for lack of time. I am sorry for the trouble.
