### ISSUE TITLE
Windows users

### ISSUE THREAD

**Issue by almeidaz** [benmatselby/sublime-phpcs#131]
Hi, 

When i try to fix file with PHP CODE beautifier (phpcb)

sublime console return :

[Phpcs] CodeBeautifier
[Phpcs] C:\php\pear\phpcbf.bat C:\Users\shiva\Desktop\papp.php -n --standard=PSR2
[Phpcs] C:\php\pear\phpcbf.bat C:\Users\shiva\Desktop\papp.php -n --standard=PSR2
[Phpcs] cwd: C:\Users\shiva
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 550, in run_
    return self.run(edit, **args)
  File "C:\Users\shiva\AppData\Roaming\Sublime Text 3\Packages\phpcs\phpcs.py", line 706, in run
    cmd.fix_standards_errors(tool, self.view.file_name())
  File "C:\Users\shiva\AppData\Roaming\Sublime Text 3\Packages\phpcs\phpcs.py", line 547, in fix_standards_errors
    fixes = CodeBeautifier().get_errors(path)
  File "C:\Users\shiva\AppData\Roaming\Sublime Text 3\Packages\phpcs\phpcs.py", line 144, in get_errors
    self.execute(path)
  File "C:\Users\shiva\AppData\Roaming\Sublime Text 3\Packages\phpcs\phpcs.py", line 314, in execute
    self.parse_report(args)
  File "C:\Users\shiva\AppData\Roaming\Sublime Text 3\Packages\phpcs\phpcs.py", line 317, in parse_report
    report = self.shell_out(args)
  File "C:\Users\shiva\AppData\Roaming\Sublime Text 3\Packages\phpcs\phpcs.py", line 181, in shell_out
    return data.decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x82 in position 1643: invalid start byte

Do you have any idea for fix this issue?
if you want more information tell me, i will supply.

Thx for help !

**Comment by benmatselby** [comment]
@almeidaz Hi there. I assume that when you run ```C:\php\pear\phpcbf.bat C:\Users\shiva\Desktop\papp.php -n --standard=PSR2``` from the command line you do not get that error?

**Comment by almeidaz** [comment]
in fact in command line i need tu use --no--patch otherwise :
'diff' is not recognized as an internal or external command,
operable program or batch file.
ex :phpcbf test.php --no-patch

**Comment by almeidaz** [comment]
I 'm installing Cygwin to get those command...in progress :)

**Comment by almeidaz** [comment]
Now i have This : 
C:\2>phpcbf test.php
Changing into directory C:\2
Processing test.php [PHP => 172 tokens in 25 lines]... DONE in 19ms (18 fixable violations)
        => Fixing file: 0/18 violations remaining [made 4 passes]... ←[32mDONE←[0m in 79ms
Array
(
    [0] => patching file test.php
    [1] => Hunk #1 FAILED at 1 (different line endings).
    [2] => 1 out of 1 hunk FAILED -- saving rejects to file test.php.rej
)
Returned: 1
Time: 448ms; Memory: 3Mb

**Comment by benmatselby** [comment]
Great, thanks for the update @almeidaz - enjoy

**Comment by giann** [comment]
Same issue here. Adding Mingw in the PATH does not solve the problem for me.

**Comment by jakewhiteley** [comment]
Same issue which persisted after adding MinGW to PATH. Using Windows 8.1 if that helps?

**Comment by almeidaz** [comment]
can you show me your phpcs.sublime-settings?

**Comment by jakewhiteley** [comment]
I "fixed" the issue by adding `--no-patch` as an argument to `phpcbf_additional_args` like so: 
```` json
"phpcbf_additional_args": {
        "--standard": "PSR2",
        "-n": "",
        "--no-patch": ""
    },
````
I have lost the original issue I found this advice in sorry.
It is also worth noting that neither installing cygwin or MinGW made diff a usable command.

**Comment by giann** [comment]
`--no-patch` does not fix the issue for me.

**Comment by Sheng-chi** [comment]
I also have the same issue. I am using Windows 10 and try to install MinGW, but it does not fix it.

**Comment by naokha** [comment]
Hi, I got the same error, tried all the previous solutions given but nothing worked for me. However, I got it working with the following actions :
1. Download sublime text PackageResourceViewer : https://packagecontrol.io/packages/PackageResourceViewer
2. Use it (Ctrl + shift + p, type packageresourceview:open resource) and choose phpcs
3. Then choose phpcs.py
4. For me the problem was the use of the decode() python function line 180. I replaced  
```python 
return data.decode()
```  
by 
```python 
return data.decode('UTF-8', 'ignore')
```  
5. Save your changes and see if it works again.

**Comment by maxazan** [comment]
Do not use full path in phpcbf_executable_path
Just "phpcbf.bat" instead of  "C:\php\pear\phpcbf.bat"
```json
{
    "phpcbf_executable_path": "phpcbf.bat",
    "phpcbf_additional_args": {
        "--standard": "PSR2",
        "-n": "",
        "--no-patch": ""
    }
}
```
