### ISSUE TITLE
Php-cs-fizer is changing my namespace

### ISSUE THREAD

**Issue by BenjaminRosell** [benmatselby/sublime-phpcs#135]
Hello there, 

Just a quick question... The Cs-Fixer is changing my namespace from 

App\Namespace 
to app\Namespace

Any ideas ?

**Comment by benmatselby** [comment]
Same as this? https://github.com/benmatselby/sublime-phpcs/issues/133

**Comment by vluzrmos** [comment]
Your source doesn't follow the PSR-0, it means the path needs to be same of namespace. Then you just need to disable that fixer.

```json
    "php_cs_fixer_additional_args": {
        "--fixers": "-psr0"
    },
```

**Comment by jcloutz** [comment]
This is the same issue that I was having in #133. It is an intentional decision by the in laravel to not adhere to the PSR-0 standard for some reason. I ended up just refactoring the namespace but as @vluzrmos said you can also disable the fixer for it.
