### ISSUE TITLE
PHPCS Explicit Path Feature

### ISSUE THREAD

**Issue by steverobbins** [benmatselby/sublime-phpcs#136]
It would be nice if PHPCS would only run on files that I've chosen in the project configuration.  Sometimes when debugging I'll modify a file that I don't own and I get all sorts of errors, because it comes from another library that doesn't follow my standard.

I'd like to be able to include an array of files/folders for my project.  Then PHPCS would only run on save if the file exists in that array.

**Comment by benmatselby** [comment]
Aye, that does sound good.

**Comment by steverobbins** [comment]
Any update on this?

**Comment by benmatselby** [comment]
I'm more than happy to accept a pull request on this @steverobbins

**Comment by steverobbins** [comment]
I would but I don't know how to write/test sublime packages.

**Comment by benmatselby** [comment]
@steverobbins Finally sat down to look at this, and you can do that already..:

```
{
    "phpcs_additional_args": {
        "--standard": "PSR2",
        "--ignore": "vendor/"
    },
}
```

The above example would run on all files except vendor/
