### ISSUE TITLE
the path is not set

### ISSUE THREAD

**Issue by ioriandy4** [benmatselby/sublime-phpcs#139]
![01](https://cloud.githubusercontent.com/assets/7553775/8285391/9e86b540-1935-11e5-83c4-ef86c1fe6233.png)
but i have seted it :"php_cs_fixer_executable_path": "D:/360yunpan/wamp_home/bin/php/php5.3.10/php-cs-fixer.phar",

**Comment by benmatselby** [comment]
Hi there @ioriandy4 That isn't the same setting. Those are two different ones.

**Comment by ioriandy4** [comment]
what is the phpcbf_executable_path?where can i download the file??

**Comment by benmatselby** [comment]
Go to:

Preferences > Package Settings > PHP Code Sniffer > Settings - User

And either copy entirely, or the bits you want from 

Preferences > Package Settings > PHP Code Sniffer > Settings - Default

In there will be the config for phpcbf_executable_path

See example here: https://github.com/benmatselby/sublime-phpcs/tree/master/example-settings

**Comment by ioriandy4** [comment]
actually i want to fomat the code. So i use the key bind
{ "keys": ["super+k", "super+f"], "command": "phpcs_fix_this_file", "args": {"tool": "CodeBeautifier"}},
but what path i should write to config phpcbf_execetable_path?

**Comment by benmatselby** [comment]
The config for phpcbf_execetable_path should be in the file I mentioned previously:

Preferences > Package Settings > PHP Code Sniffer > Settings - User

**Comment by leotm** [comment]
I installed via pear, so only had:
`C:\xampp\php\phpcs.bat`
`C:\xampp\php\phpcbf.bat`
Missing `php-cs-fixer.bat`.
Running  _Xdebug_, so avoiding _Composer_ atm.
Grabbed and extracted ` php-cs-fixer.phar`, but not using _symfony_ and unsure about _sebastian_.
Ended up `$ curl -L https://github.com/FriendsOfPHP/PHP-CS-Fixer/releases/download/v2.0.0/php-cs-fixer.phar -o php-cs-fixer` and creating my own batch file.
Pretty long winded :(

**Comment by benmatselby** [comment]
@leotm Hi there

What is pretty long winded?

**Comment by leotm** [comment]
Getting `php-cs-fixer` working without package managers while pretty new to all this.

**Comment by benmatselby** [comment]
Hi @leotm 

You probably want to raise that with the tool owners [here ](https://github.com/FriendsOfPHP/PHP-CS-Fixer) as that isn't something that I'm in control of.

This plugin assumes you have all the tools installed, as this plugin links the underlying tool to Sublime Text.

**Comment by leotm** [comment]
Sure makes sense and will do, thanks again.
