### ISSUE TITLE
Hi I got a this error message

### ISSUE THREAD

**Issue by pipecivil** [benmatselby/sublime-phpcs#145]
[Phpcs] ERROR: option "- " not known.

problem thing is 
Writing file /Volumes/Myimportant/web/www/index.php with encoding UTF-8
[Phpcs] /usr/local/bin/phpcs -l -d display_errors=On /Volumes/Myimportant/web/www/index.php
[Phpcs] /usr/local/bin/phpcs -l -d display_errors=On /Volumes/Myimportant/web/www/index.php
[Phpcs] cwd: /Users/mac
[Phpcs] ERROR: option "- " not known.

in console not problem only problem on the sublime text2 

other line is good
[Phpcs] /usr/local/bin/phpcs --report=checkstyle -n --standard=/Users/mac/pear/share/pear/PHP/CodeSniffer/Standards/MySource/ruleset.xml /Volumes/Myimportant/web/www/index.php
[Phpcs] /usr/local/bin/phpcs --report=checkstyle -n --standard=/Users/mac/pear/share/pear/PHP/CodeSniffer/Standards/MySource/ruleset.xml /Volumes/Myimportant/web/www/index.php
[Phpcs] cwd: /Users/mac
[Phpcs] <?xml version="1.0" encoding="UTF-8"?>
<checkstyle version="2.3.4">

what's wrong with me

**Comment by benmatselby** [comment]
@pipecivil Your config is incorrect. Look at this line:

```
[Phpcs] /usr/local/bin/phpcs -l -d display_errors=On /Volumes/Myimportant/web/www/index.php
```

You are using phpcs with the php linting options. Update your php path and it should work fine. There are example configs in the repo

**Comment by pipecivil** [comment]
thank you very much !!
