### ISSUE TITLE
Is there a way to exclude a specific rule?

### ISSUE THREAD

**Issue by khrizt** [benmatselby/sublime-phpcs#146]
Hi,

Looking at the settings I don't know if there's an option to exclude specific rules from the coding standard fixer, perfection would be excluding a rule from a certain type of files, but that probably is very difficult.

Thanks

**Comment by benmatselby** [comment]
@khrizt You would do this by a custom coding standard for PHPCS.. This plugin wraps PHPCS, which allows you to do that, so I don't think this plugin should add an extra layer on top of that?

**Comment by khrizt** [comment]
Thanks, you are totally right.
