### ISSUE TITLE
Commands not working for fixer and beautifier

### ISSUE THREAD

**Issue by designermonkey** [benmatselby/sublime-phpcs#148]
I have the package installed correctly, and have it configured to find the executables.

Everything works ok when set to function on save, but the choices from the command palette (other than sniff, and the on save switcher) just refuse to do anything.

**Comment by designermonkey** [comment]
Sorry, this is on Mac OS Mavericks.

**Comment by benmatselby** [comment]
Hi @designermonkey Can you provide your config please, and the output in the console of when the commands are selected.. You will need show_debug: true in your config for this please

**Comment by designermonkey** [comment]
When switching the debug on, it works fine :(

**Comment by designermonkey** [comment]
```
[Phpcs] Fixer
[Phpcs] /usr/local/bin/php-cs-fixer fix /Users/designermonkey/Projects/Embark/_packages/persistence-elasticsearch/src/untitled.php --verbose
[Phpcs] /usr/local/bin/php-cs-fixer fix /Users/designermonkey/Projects/Embark/_packages/persistence-elasticsearch/src/untitled.php --verbose
[Phpcs] cwd: /Users/designermonkey
[Phpcs] F
Legend: ?-unknown, I-invalid file syntax, file ignored, .-no changes, F-fixed, E-error
   1) /xxx/xxx/src/untitled.php (function_declaration, blankline_after_open_tag, psr0, braces)
Fixed all files in 0.149 seconds, 4.750 MB memory used

reloading /xxx/xxx/src/untitled.php
```

**Comment by benmatselby** [comment]
@designermonkey  Debug only echoes stuff to the console, so not sure that would have any bearing..

You OK for me to close the issue until we have something to go on please?

**Comment by designermonkey** [comment]
ok
