### ISSUE TITLE
Why is phpcs catching .html files?

### ISSUE THREAD

**Issue by corysimmons** [benmatselby/sublime-phpcs#149]
![image](https://cloud.githubusercontent.com/assets/224636/12936129/32a13298-cf69-11e5-8046-585c8f53c024.png)

**Comment by benmatselby** [comment]
Hi @corysimmons Probably because it thinks it is a PHP file as per https://github.com/benmatselby/sublime-phpcs/blob/master/phpcs.py#L622

Can you provide your config please?

**Comment by corysimmons** [comment]
I'm pretty sure it's just whatever config phpcs 2.5.1 defaults to.

**Comment by corysimmons** [comment]
Oh I'm so sorry, I'm not even using your plugin, I'm using SublimeLinter.

Thoughts on trying to get this merged into https://github.com/SublimeLinter/SublimeLinter-phpcs ?

**Comment by benmatselby** [comment]
Hi @corysimmons Sorry, I'm unsure what you are asking me here? You want this plugin to merge with SublimeLinter? Not sure what benefit that would add, it's your choice to use either?

**Comment by corysimmons** [comment]
Sorry, does your plugin allow for automatic linting?

![image](https://cloud.githubusercontent.com/assets/224636/12955388/cbadf066-cff0-11e5-8d18-de4f35251a1f.png)

Or do you have to click on each file individually?

**Comment by benmatselby** [comment]
Hi @corysimmons

This plugin does not auto lint and I have no plans to support that.

**Comment by corysimmons** [comment]
Okay, no problem. Thanks.
