### ISSUE TITLE
Disable specific fixer

### ISSUE THREAD

**Issue by rikless** [benmatselby/sublime-phpcs#152]
Hello,

I'm trying to ignore psr0 withe phpcs.

I've tried php_cs_fixer_fixers_list="-psr0" or fixers=-psr0 in additionnal args, but this doesn't works.

What's the correct syntax ?

```
"phpcs_additional_args": {
        "--fixers": "-psr0",
        "--standard": "PSR2",
        "-n": "",
        "php_cs_fixer_fixers_list":"-psr0",
    },
```

**Comment by benmatselby** [comment]
hi @rikless What do you usually do on the command line? It looks like you are mixing phpcs and php_cs_fixer settings here.

**Comment by benmatselby** [comment]
Closing as unsure what is trying to be achieved and no feedback.. If you can update with what you are wanting to do, I may be able to help
