### ISSUE TITLE
Adding phpmd rules in phpmd_additional_args

### ISSUE THREAD

**Issue by omargourari** [benmatselby/sublime-phpcs#153]
I'd like to know if the following is the correct way to add phpmd rules as additional args cause I'd like to apply the larger rules coverage by adding them all.

`  "phpmd_additional_args": {
    "cleancode,codesize,controversial,design,naming,unusedcode": ""
  },`

**Comment by benmatselby** [comment]
@omargourari Yes, that is also the way I have mine defined:

```
    "phpmd_additional_args": {
        "codesize,naming,unusedcode": ""
    },
```
