### ISSUE TITLE
Inclusion of "PHP Static Analysis" as another command

### ISSUE THREAD

**Issue by absalomedia** [benmatselby/sublime-phpcs#154]
There's a new linter in development here:

https://phpsa.dmtry.me/

Any long term plans to include it as part of the Sublime PHP CS feature set?

**Comment by benmatselby** [comment]
Hi @absalomedia - Honestly, no.. I've switched to using phpStorm, so I'm not actively using SublimeText as a development environment anymore.

I would probably merge it in if someone built it, if it was simply adding another shell command, and it didn't need to change any other structures, and was configurable as on/off etc

**Comment by benmatselby** [comment]
Closing this down. As per my previous comment I'm not really using Sublime Text now a days. I think my aim at the moment is to try and support what we have but not add more.
