### ISSUE TITLE
Install sublime-phpcs on windows with dependencies

### ISSUE THREAD

**Issue by abumalick** [benmatselby/sublime-phpcs#157]
Hello,
It was very difficult to make it work on windows with XAMPP, here is some instruction to install it. It would be great that you include this somewhere to help people that want to install sublime-phpcs on windows with dependencies.

`cd C:\xampp\php`
It seems there is a config problem with pear under XAMPP 7.0.6: 
If I try to `pear install` it throw : `ERROR: failed to mkdir C:\php\pear\tests\PHP_CodeSniffer\CodeSniffer\Core\File` here is the [solution](http://subharanjan.com/error-failed-mkdir-cphppeartestsphp_codesniffercodesniffercorefile-solved/) : 
```
pear config-set doc_dir C:\xampp\php\pear
pear config-set cfg_dir C:\xampp\php\pear
pear config-set data_dir C:\xampp\php\pear
pear config-set test_dir C:\xampp\php\pear
pear config-set www_dir C:\xampp\php\pear
```
We can install PHP CodeSniffer (phpcs and phpbf):
`pear install PHP_CodeSniffer`

And install phpmd:
```
pear channel-discover pear.pdepend.org
pear channel-discover pear.phpmd.org
pear install phpmd/PHP_PMD
```
We note path of all executables with:
```
where phpcs
where phpcbf
where phpmd
```
In Sublime Text We can install sublime-phpcs package with Package control and change the config in sublime text like this : 
```
{
    "phpcs_executable_path": "C:\\xampp\\php\\phpcs.bat",

    "phpcbf_executable_path": "C:\\xampp\\php\\phpcbf.bat",

    "phpcs_php_path": "C:\\xampp\\php\\php.exe",

    "phpmd_executable_path": "C:\\xampp\\php\\phpmd.bat",

}
```
Coudn't find out how to make facebook/sniff/Scheck and php-cs-fixer in windows, any help appreciated.
Thanks to [subharanjan for his tutorial](http://subharanjan.com/setup-php-codesniffer-windows-machine/) that helped me.
Thanks to benmatselby for his work making this plugin

**Comment by benmatselby** [comment]
Hi @abumalick - Thanks for the feedback, but I wouldn't really want to provide installation instructions for the tools that this plugin wraps around, as that would be an overhead on me, when in reality this best sits with the tools you want to use.

**Comment by abumalick** [comment]
It is an avantage of collaboration. You can let collaborators maintain the doc for you. 
I can make modifications and make a pull request if you accept.
-- 
Abdullah Hilson
abdullah.hilson@gmail.com
00201229779075
