### ISSUE TITLE
Regarding the phpcs.xml source , new feature on version 6.7.0

### ISSUE THREAD

**Issue by sameernyaupane** [benmatselby/sublime-phpcs#162]
Hi,

So to set our own standard from a phpcs.xml source, should I set the standard to "MySource"?

eg.

```"phpcs":
        {
            "phpcs_additional_args":
            {
                "--standard": "MySource"
            }
        }
```

Thanks

**Comment by benmatselby** [comment]
@sameernyaupane Hi there.. You would need to add the phpcs.xml into the project path and then remove the config above so it used what it found instead. You are essentially delegating the picking of the standard to phpcs itself rather than the plugin setting it for you

**Comment by sameernyaupane** [comment]
Well if I remove that config, it defaults to psr2.

```[Phpcs] C:\Users\Lenovo\AppData\Roaming\Composer\vendor\bin\phpcs.bat --report=checkstyle -n --standard=PSR2````

It is not able to find the phpcs.xml in the root project directory automatically at all.

**Comment by benmatselby** [comment]
Hi @sameernyaupane 

Apologies, this is what config I have

```
"phpcs_additional_args": {
    },
```

So it's blank which means it is overriden, and doesn't pull in standard that ships with plugin of PSR2

**Comment by sameernyaupane** [comment]
Thanks it works now.

But why don't the errors come up with line highlight and errors list like for psr2? I only see the errors on the sublime console.

```----------------------------------------------------------------------

FOUND 1 ERROR AFFECTING 1 LINE

----------------------------------------------------------------------

 76 | ERROR | [x] Expected 1 spaces before closing bracket; 0 found

----------------------------------------------------------------------

PHPCBF CAN FIX THE 1 MARKED SNIFF VIOLATIONS AUTOMATICALLY

----------------------------------------------------------------------
```

**Comment by benmatselby** [comment]
@sameernyaupane Can you post your config please, I would imagine it has been turned off 

```
"phpcs_show_gutter_marks": true,
"phpcs_outline_for_errors": true,
"phpcs_show_errors_in_status": true,
```

**Comment by sameernyaupane** [comment]
Here are my user phpcs sublime settings:

```
{
    "phpcs_additional_args": {
        "--standard": "PSR2",
        "-n": ""
    },
    "phpcbf_additional_args": {
        "--standard": "PSR2",
        "-n": ""
    },
    "phpcs_executable_path": "C:\\Users\\Lenovo\\AppData\\Roaming\\Composer\\vendor\\bin\\phpcs.bat",
	"phpcbf_executable_path": "C:\\Users\\Lenovo\\AppData\\Roaming\\Composer\\vendor\\bin\\phpcbf.bat",
    "phpmd_executable_path": "",
    "php_cs_fixer_executable_path": "",
    "phpcs_execute_on_save": false,
    "show_debug": true,
}```

By default those seem to be on

```
    // Show the errors in the gutter
    "phpcs_show_gutter_marks": true,

    // Show outline for errors
    "phpcs_outline_for_errors": true,

    // Show the errors in the status bar
    "phpcs_show_errors_in_status": true,
```

**Comment by benmatselby** [comment]
@sameernyaupane What happens if you define then in your user settings too ?

**Comment by sameernyaupane** [comment]
If I define them in the user settings, nothing changes. Same with defining them in project settings.

**Comment by benmatselby** [comment]
Hi @sameernyaupane Do the errors work when you don't define a local phpcs.xml file? If so, then it may simply be that your phpcs.xml doesn't have any sniffs that produce errors? There is no difference with this patch.

**Comment by sameernyaupane** [comment]
Hmm that could be the case. I'll let you know if it is otherwise. Thanks a lot again :)
