### ISSUE TITLE
Hotkey/ Keyboard shortcut to sniff a file.

### ISSUE THREAD

**Issue by sameernyaupane** [benmatselby/sublime-phpcs#163]
Is there a hotkey/keyboard shortcut to sniff a file?

Thanks

**Comment by benmatselby** [comment]
Hi @sameernyaupane That is discussed in the [Readme](https://github.com/benmatselby/sublime-phpcs#what-other-key-bindings-can-i-setup)

**Comment by sameernyaupane** [comment]
thanks, got it. 👍
