### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by zhiephie** [benmatselby/sublime-phpcs#164]
Console
```
[Phpcs] Project files:
[Phpcs]  Current: None
[Phpcs]  Last Known: None
[Phpcs] No project file defined, therefore skipping reload
Unable to open /home/zhiephie/.config/sublime-text-3/Packages/Default/Preferences.sublime-settings
```

phpcs setting
https://gist.github.com/zhiephie/71ecc1620248ffd0e87bb5b2f9afab7f

**Comment by benmatselby** [comment]
Thanks for raising @zhiephie - would it be possible to provide slightly more detail? What OS?, what are you expecting to run? Which action are you running? Right clicking and sniffing, or on save or?

**Comment by zhiephie** [comment]
@benmatselby Ok, Os Ubuntu 16.04.

Log on console
```
[Phpcs] Project files:
[Phpcs]  Current: None
[Phpcs]  Last Known: None
[Phpcs] No project file defined, therefore skipping reload
[Phpcs] Project files:
[Phpcs]  Current: None
[Phpcs]  Last Known: None
[Phpcs] No project file defined, therefore skipping reload
[Phpcs] Project files:
[Phpcs]  Current: None
[Phpcs]  Last Known: None
[Phpcs] No project file defined, therefore skipping reload
[Phpcs] Project files:
[Phpcs]  Current: None
[Phpcs]  Last Known: None
[Phpcs] No project file defined, therefore skipping reload
```
phpcs (work running manual)
phpmd (work running manual)
PHP CS Fixer (work running manual)
Scheck (work running manual)
PHP Code Beautifier(work running manual)

Right clicking and sniffing, or on save or? : ``Event save a file.``

**Comment by benmatselby** [comment]
Hi @zhiephie Based on your settings, it isn't configured to run on save:

```
 // Execute the sniffer on file save
    "phpcs_execute_on_save": false,
```

So switch that to true
