### ISSUE TITLE
[sublime] Weird error in console

### ISSUE THREAD

**Issue by BramRoets** [benmatselby/sublime-phpcs#165]
[Phpcs] /Users/_/.composer/vendor/bin/phpcs --report=checkstyle -n --standard=PSR2 /..file.php
[Phpcs] /Users/_/.composer/vendor/bin/phpcs --report=checkstyle -n --standard=PSR2 /..file.php
[Phpcs] cwd: /*
[Phpcs] Valet requires Brew to be installed on your Mac.
[Phpcs] Linter found 0 errors
[Phpcs] Sniffer found 0 errors

I have no idea what valet has to do with phpcs. (folders are hidden by *)

**Comment by benmatselby** [comment]
I have no idea what Valet is i'm afraid, so not sure I can help here

**Comment by BramRoets** [comment]
It's a package also installed by composer. I have no idea why it's called from within phpcs. Do you have any idea why this program is ran by phpcs?

**Comment by benmatselby** [comment]
I don't, sorry

**Comment by benmatselby** [comment]
@BramRoets If you run the following just from your command line/terminal

```
 /Users//.composer/vendor/bin/phpcs --report=checkstyle -n --standard=PSR2 /..file.php
```

What happens?

**Comment by BramRoets** [comment]
Output: 
<?xml version="1.0" encoding="UTF-8"?>
<checkstyle version="2.7.0">
</checkstyle>

**Comment by benmatselby** [comment]
@BramRoets If there are no results, there wouldn't be anything to show in the plugin?

**Comment by BramRoets** [comment]
Even when there are mistakes, non are show. Example output of a file with mistakes: 

`<?xml version="1.0" encoding="UTF-8"?>
<checkstyle version="2.7.0">
<file name="/*.php">
 <error line="63" column="89" severity="error" message="Each PHP statement must be on a line by itself" source="Generic.Formatting.DisallowMultipleStatements.SameLine"/>
 <error line="63" column="103" severity="error" message="Each PHP statement must be on a line by itself" source="Generic.Formatting.DisallowMultipleStatements.SameLine"/>
 <error line="63" column="117" severity="error" message="Each PHP statement must be on a line by itself" source="Generic.Formatting.DisallowMultipleStatements.SameLine"/>
 <error line="63" column="131" severity="error" message="Each PHP statement must be on a line by itself" source="Generic.Formatting.DisallowMultipleStatements.SameLine"/>
 <error line="63" column="145" severity="error" message="Each PHP statement must be on a line by itself" source="Generic.Formatting.DisallowMultipleStatements.SameLine"/>
 <error line="63" column="159" severity="error" message="Each PHP statement must be on a line by itself" source="Generic.Formatting.DisallowMultipleStatements.SameLine"/>
 <error line="71" column="9" severity="error" message="Visibility must be declared on property &quot;$schedule&quot;" source="PSR2.Classes.PropertyDeclaration.ScopeMissing"/>
 <error line="76" column="9" severity="error" message="Visibility must be declared on property &quot;$schedule&quot;" source="PSR2.Classes.PropertyDeclaration.ScopeMissing"/>
 <error line="79" column="9" severity="error" message="Visibility must be declared on property &quot;$schedule&quot;" source="PSR2.Classes.PropertyDeclaration.ScopeMissing"/>
 <error line="80" column="5" severity="error" message="Line indented incorrectly; expected 0 spaces, found 4" source="Generic.WhiteSpace.ScopeIndent.IncorrectExact"/>
 <error line="80" column="5" severity="error" message="Closing brace indented incorrectly; expected 0 spaces, found 4" source="Squiz.WhiteSpace.ScopeClosingBrace.Indent"/>
 <error line="87" column="5" severity="error" message="Line indented incorrectly; expected 0 spaces, found 4" source="Generic.WhiteSpace.ScopeIndent.IncorrectExact"/>
 <error line="90" column="5" severity="error" message="Line indented incorrectly; expected 0 spaces, found 4" source="Generic.WhiteSpace.ScopeIndent.IncorrectExact"/>
</file>
</checkstyle>`

**Comment by benmatselby** [comment]
Hi @BramRoets Is that the output in the console of SublimeText or the terminal? If terminal, can you get the output from SublimeText? Also, what configuration do you have in Sublime Text please?

**Comment by jpmurray** [comment]
I came in to say exactly the same, seems that Valet is breaking things, because running each tools on the terminal will results in the wanted behavior, but running it from sublime-phpcs, it seems like things just won't work.

FYI, Valet is a quick php server, developped by the guys at Laravel.: https://github.com/laravel/valet/.

Now, here is the sublime console output I have when saving a PHP file (note, I have everything properly activated):

```
[Phpcs] Project files:
[Phpcs]  Current: None
[Phpcs]  Last Known: None
[Phpcs] No project file defined, therefore skipping reload
[Phpcs] /Users/jpmurray/.composer/vendor/bin/php-cs-fixer fix /Users/jpmurray/Repositories/test/app/User.php --verbose
[Phpcs] /Users/jpmurray/.composer/vendor/bin/php-cs-fixer fix /Users/jpmurray/Repositories/test/app/User.php --verbose
[Phpcs] cwd: /Users/jpmurray
[Phpcs] Valet requires Homebrew to be installed on your Mac.
[Phpcs] /Users/jpmurray/.composer/vendor/bin/phpcbf /Users/jpmurray/Repositories/test/app/User.php --standard=PSR2 -n
[Phpcs] /Users/jpmurray/.composer/vendor/bin/phpcbf /Users/jpmurray/Repositories/test/app/User.php --standard=PSR2 -n
[Phpcs] cwd: /Users/jpmurray
[Phpcs] Valet requires Homebrew to be installed on your Mac.
[Phpcs] php -l -d display_errors=On /Users/jpmurray/Repositories/test/app/User.php
[Phpcs] php -l -d display_errors=On /Users/jpmurray/Repositories/test/app/User.php
[Phpcs] cwd: /Users/jpmurray
[Phpcs] No syntax errors detected in /Users/jpmurray/Repositories/test/app/User.php

[Phpcs] /Users/jpmurray/.composer/vendor/bin/phpcs --report=checkstyle --standard=PSR2 -n /Users/jpmurray/Repositories/test/app/User.php
[Phpcs] /Users/jpmurray/.composer/vendor/bin/phpcs --report=checkstyle --standard=PSR2 -n /Users/jpmurray/Repositories/test/app/User.php
[Phpcs] cwd: /Users/jpmurray/Repositories/test/app
[Phpcs] Valet requires Homebrew to be installed on your Mac.
[Phpcs] /Users/jpmurray/.composer/vendor/bin/phpmd /Users/jpmurray/Repositories/test/app/User.php text codesize,unusedcode,naming
[Phpcs] /Users/jpmurray/.composer/vendor/bin/phpmd /Users/jpmurray/Repositories/test/app/User.php text codesize,unusedcode,naming
[Phpcs] cwd: /Users/jpmurray
[Phpcs] Valet requires Homebrew to be installed on your Mac.
[Phpcs] Linter found 0 errors
[Phpcs] Sniffer found 0 errors
[Phpcs] MessDetector found 0 errors
```

**Comment by jpmurray** [comment]
Welp, seems like I've found the culprit! Follow this for explanation, but also, installing it just make phpcs work again!

https://packagecontrol.io/packages/Fix%20Mac%20Path

**Comment by benmatselby** [comment]
Closing as it doesn't seem related to this plugin and there is a workaround above.
