### ISSUE TITLE
Ignore Argument not working

### ISSUE THREAD

**Issue by chrisblackwell** [benmatselby/sublime-phpcs#172]
I use snakecase for all my test method names, which is not part of PSR2. I have it set to ignore my `tests` directory, but PHPCS still seem to run on those files. 

Here are my argument settings:
```
"phpcs_additional_args": {
    "--standard": "PSR2",
    "--ignore": "*/tests/*,*/database/*",
    "-n": ""
},
"phpcs_linter_run": true
```

**Comment by benmatselby** [comment]
@chrisblackwell Hi there, can you turn on the debug option and paste the output here when you run it. And can you then do the same in your normal terminal so we can see the difference?

**Comment by benmatselby** [comment]
Hi @chrisblackwell I'm going to close the ticket.. Feel free to add a comment with the output as mentioned above if you get chance. Thanks
