### ISSUE TITLE
Issue on retina display

### ISSUE THREAD

**Issue by m5taha5m** [benmatselby/sublime-phpcs#173]
Gutter icon is not showing properly on my new macbook pro 2016. Here an screenshot attached.
![screen shot 2017-05-18 at 10 04 43](https://cloud.githubusercontent.com/assets/3314387/26187999/d6720cfc-3bb1-11e7-998e-a435cf2e1127.png)

**Comment by benmatselby** [comment]
Hi there @m5taha5m  I don't really think this is a plugin issue, but rather a Sublime Text. We just state we want a dot or something, and then Sublime Text renders it for us
