### ISSUE TITLE
Standards with the letters "and" in them have "and" replaced with a ",", and don't work

### ISSUE THREAD

**Issue by jhaagsma** [benmatselby/sublime-phpcs#185]
Standards with the letters "and" in them have "and" replaced with a ",", and subsequently don't work

For example, adding NeutronStandard to the list of standards results in "NeutronSt,ard" to show up in the "Switch coding standard" list, and that standard no longer works.

I took a glance through the code and didn't see how this should be possible, but phpcs runs "NeutronStandard" just fine from the command line, so I'm assuming it's got to be in this package somewhere.

**Comment by benmatselby** [comment]
Hey @jhaagsma 

Not sure if you're still using this plugin, but this issue is now resolved both on `main` and `master`. I'll do a release later today, but I think we are waiting on https://github.com/wbond/package_control_channel/pull/8833 to be merged before releases will work :)

**Comment by jhaagsma** [comment]
Nice to see this got fixed eventually! I'm not actively using it, though I do need to fire up that environment for my hobby projects sometime...
