### ISSUE TITLE
Why this package is marked as "DEPRECATED" in the title?

### ISSUE THREAD

**Issue by hoanglan87** [benmatselby/sublime-phpcs#187]
Why this package is marked as "DEPRECATED" in the title? Any alternative or can we live with deprecated one?

**Comment by benmatselby** [comment]
Hi there @hoanglan87 . I no longer use Sublime Text as I have moved over to Visual Studio Code. Those questions seem more related to you? As far as I know, this plugin still works, but I won't be adding any more features to it. Hope this helps you decide.
