### ISSUE TITLE
Update url 

### ISSUE THREAD

**Issue by JamesVanWaza** [benmatselby/sublime-phpcs#191]
The url is https://benmatselby.dev/sublime-phpcs/ update it in the front page

**Comment by benmatselby** [comment]
Hey @JamesVanWaza Did you mean this

![Screenshot 2020-01-11 at 20 02 30](https://user-images.githubusercontent.com/178634/72210026-50ee4300-34ad-11ea-951d-65d4fa588277.png)

If so, I've now resolved this, thanks for flagging. If not, i'm unclear which bit you mean.

**Comment by JamesVanWaza** [comment]
@benmatselby  Yes, that's what I meant. Thanks.
