### ISSUE TITLE
[WinError 2] The system cannot find the file specified

### ISSUE THREAD

**Issue by Captain272** [benmatselby/sublime-phpcs#194]
from selenium import webdriver
from bs4 import BeautifulSoup
import requests as rq
import pandas as pd

driver = webdriver.Chrome()
product=[]
prices=[]
rating =[]
driver.get("https://www.flipkart.com/search?q=mobiles&sid=tyy%2C4io&as=on&as-show=on&otracker=AS_QueryStore_OrganicAutoSuggest_2_18_na_pm_na&otracker1=AS_QueryStore_OrganicAutoSuggest_2_18_na_pm_na&as-pos=2&as-type=RECENT&suggestionId=mobiles%7CMobiles&requestId=856dedac-760a-46ae-aa63-a3ab78882a7b&as-searchtext=high+rated+mobiles&p%5B%5D=facets.price_range.from%3D16000&p%5B%5D=facets.price_range.to%3DMax")
content =driver.page_source
soup = rq(content)
for a in soup.findAll('a',href=True, attrs={'class':'_31qSD5'}):
    name=a.find('div', attrs={'class':'_3wU53n'})
    price=a.find('div', attrs={'class':'_1vC4OE _2rQ-NK'})
    rating=a.find('div', attrs={'class':'hGSR34 _2beYZw'})
    products.append(name.text)
    prices.append(price.text)
    ratings.append(rating.text)
df = pd.DataFrame({'Product Name':products,'Price':prices,'Rating':ratings}) 
df.to_csv('products.csv', index=False, encoding='utf-8')

ERROR 👍 
s.py", line 1307, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

ERROR 🥇 
selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home

**Comment by benmatselby** [comment]
Hey. What’s the above error please?

**Comment by benmatselby** [comment]
Thanks for raising @Captain272. I'm going to close this down due to inactivity. From the error I can see above, this doesn't seem related to this project. Please re-open with some more information if you believe this is still an issue with this project 😄
