### ISSUE TITLE
phpcs_additional_args --runtime-set not working due to empty duplicate

### ISSUE THREAD

**Issue by MichelleBlanchette** [benmatselby/sublime-phpcs#206]
_Relates to issue https://github.com/benmatselby/sublime-phpcs/issues/155_

I'm wanting to use `--runtime-set testVersion 5.6-` but it isn't working. It seems the argument gets duplicated with an empty value, making the original value obsolete.

_phpcs.sublime-settings_
```
    "phpcs_additional_args": {
        "-n": "",
        "--standard": "WordPress,PHPCompatibilityWP",
        "--runtime-set": "testVersion 5.6-"
    },
```

_Sublime Console Output_
```
[Phpcs] phpcs --report=checkstyle --runtime-set testVersion 5.6 --runtime-set --standard=WordPress,PHPCompatibilityWP -n <REDACTED>.php
```

Attempted workarounds that didn't resolve the issue:
- Change order of `phpcs_additional_args` keys
- Add literal double quotes to argument value: `"--runtime-set": "\"testVersion 5.6-\""`

**Environment**
- Sublime Text Build 4143
- Phpcs v2020.01.17.08.29.37 (via Package Control)

**Comment by MichelleBlanchette** [comment]
I'm not a Python developer, but I think the for-loop just needs to be continued after the `--runtime-set` arg key and its value are appended to the set of arguments. The duplicate is likely caused by the `args.append(arg)` at the end of the loop.

https://github.com/benmatselby/sublime-phpcs/blob/c516c15ff9567a81c81363f1b9016101ca2e618e/phpcs.py#L214-L222

**Comment by MichelleBlanchette** [comment]
I understand this package is no longer maintained, so I've switched to using the main `SublimeLinter` package set: https://packagecontrol.io/packages/SublimeLinter-phpcs

**Comment by benmatselby** [comment]
Hey @MichelleBlanchette 

Apologies, you're right, I don't use SublimeText anymore. I hope SublimeLinter meets your requirements :)
