### ISSUE TITLE
Per Project Settings

### ISSUE THREAD

**Issue by fstrube** [benmatselby/sublime-phpcs#32]
Is there a way to specify per-project settings? For instance I would like my Magento projects to use a different standard than my CakePHP projects. I would like to do:

_magento.sublime-project_

```
{
    "folders": ["/path/to/project"],
    "settings":
    {
        "phpcs_additional_args": {
            "--standard": "Zend"
        }
    }
}
```

**Comment by tgfisher** [comment]
> Slightly different: http://www.soulbroken.co.uk/2013/04/sublime-phpcs-now-supports-project-based-settings/ It is essentially named spaced within phpcs.

This link is broken. Can you add the documentation to the wiki or readme?

**Comment by handrus** [comment]
Leaving a example here for anyone that might find this and the broken link. Your .project file should look something like this:
```
{
	"folders":
	[
		{
			"folder_exclude_patterns":
			[
				"node_modules/*",
				"gulp/*",
				"builds/*",
				"src/themes/natura/assets/sass/.sass-cache"
			],
			"path": "/home/handrus/Projects/Taller/xpto"
		}
	],
	"settings":
	{
		"phpcs":
		{
			"phpcs_additional_args":
			{
				"--standard": "/path/to/.composer/vendor/drupal/coder/coder_sniffer/Drupal"
			}
		}
	}
}
```
Of course this is a example to apply Drupal code sniffer. This could be anything.
Whatever you can have on this package settings it can be overwritten under the settings -> phpcs

**Comment by benmatselby** [comment]
Thanks @handrus for writing this up - appreciate it.

I've updated the github page with it: http://benmatselby.github.io/sublime-phpcs/#project-based-settings
