### ISSUE TITLE
PHPCS not working properly

### ISSUE THREAD

**Issue by Exadra37** [benmatselby/sublime-phpcs#46]
PHPCS
- installed using Package Control

PHP_CodeSniffer 
- installed using Pear.
- works fine by command line and in Sublime Text2.

PHP-CS-Fixer
- installed using:
  <pre><code>sudo wget http://cs.sensiolabs.org/get/php-cs-fixer.phar -O /usr/local/bin/php-cs-fixer
  sudo chmod a+x /usr/local/bin/php-cs-fixer</code></pre>
- do not work properly in sublime text, because will not identify all the fixers, missing some ones.
- if i use from command line :
  
  <pre><code>php-cs-fixer fix /home/username/public_html/tvcabo-testes/modules/old_files/combinacoes.php --level=all</code></pre>
  
  i get this message
  
  <pre><code>! Class combinacoes in /home/username/public_html/tvcabo-testes/modules/old_files/combinacoes.php should have at least a vendor namespace according to PSR-0 rules</code></pre>
- by command line or  on save in sublime tex,t will ignore fixer visibility , for example, but will use the fixer phpdoc_params correctely.

PHPPMD
- installed using Pear.
  <pre><code>pear channel-discover pear.phpmd.org
  pear channel-discover pear.pdepend.org
  pear install --alldeps phpmd/PHP_PMD</code></pre>
- works from command line, but i don't get any feedback in sublime text 2.
  <pre><code>phpmd /home/username/public_html/tvcabo-testes/modules/old_files/combinacoes.php text codesize,unusedcode,naming</code></pre>
- i get this message from command line:
  <pre><code>/home/username/public_html/tvcabo-testes/modules/old_files/combinacoes.php:7   Avoid excessively long variable names like $nr_Elementos_a_combinar. Keep variable name length under 20.
  /home/username/public_html/tvcabo-testes/modules/old_files/combinacoes.php:7   Avoid excessively long variable names like $nr_Elementos_por_Combinacao. Keep variable name length under 20.
  /home/username/public_html/tvcabo-testes/modules/old_files/combinacoes.php:9   Avoid unused local variables such as '$numero_Combinacoes'.
  /home/username/public_html/tvcabo-testes/modules/old_files/combinacoes.php:23  The method gerar_Combinacoes_Possiveis() has a Cyclomatic Complexity of 12. The configured cyclomatic complexity threshold is 10.
  /home/username/public_html/tvcabo-testes/modules/old_files/combinacoes.php:70  Avoid excessively long variable names like $combinacoes_efectuadas. Keep variable name length under 20.
  /home/username/public_html/tvcabo-testes/modules/old_files/combinacoes.php:75  Avoid excessively long variable names like $combinacoes_possiveis. Keep variable name length under 20.</code></pre>

LINTER
- Don work also.

default phpcs.sublime-settings:

<pre><code>{
    // Plugin settings

    // Turn the debug output on/off
    "show_debug": false,

    // Which file types (file extensions), do you want the plugin to
    // execute for
    "extensions_to_execute": ["php"],

    // Execute the sniffer on file save
    "phpcs_execute_on_save": true,

    // Show the error list after save.
    "phpcs_show_errors_on_save": true,

    // Show the errors in the gutter
    "phpcs_show_gutter_marks": true,

    // Show outline for errors
    "phpcs_outline_for_errors": true,

    // Show the errors in the status bar
    "phpcs_show_errors_in_status": true,

    // Show the errors in the quick panel so you can then goto line
    "phpcs_show_quick_panel": true,

    // PHP_CodeSniffer settings

    // Do you want to run the phpcs checker?
    "phpcs_sniffer_run": true,

    // Execute the sniffer on file save
    "phpcs_command_on_save": true,

    // It seems python/sublime cannot always find the phpcs application
    // If empty, then use PATH version of phpcs, else use the set value
    "phpcs_executable_path": "",

    // Additional arguments you can specify into the application
    //
    // Example:
    // {
    //     "--standard": "PEAR",
    //     "-n"
    // }
    "phpcs_additional_args": {
        "--standard": "PEAR",
        "-n": ""
    },

    // PHP-CS-Fixer settings

    // Fix the issues on save
    "php_cs_fixer_on_save": false,

    // Show the quick panel
    "php_cs_fixer_show_quick_panel": false,

    // Path to where you have the php-cs-fixer installed
    "php_cs_fixer_executable_path": "",

    // Additional arguments you can specify into the application
    //
    // Example:
    // {
    //     "--level": "all"
    // }
    "php_cs_fixer_additional_args": {
        "--level": "all"
    },

    // PHP Linter settings

    // Are we going to run php -l over the file?
    "phpcs_linter_run": true,

    // Execute the linter on file save
    "phpcs_linter_command_on_save": true,

    // It seems python/sublime cannot always find the php application
    // If empty, then use PATH version of php, else use the set value
    "phpcs_php_path": "",

    // What is the regex for the linter? Has to provide a named match for 'message' and 'line'
    "phpcs_linter_regex": "(?P<message>.*) on line (?P<line>\\d+)",

    // PHP Mess Detector settings

    // Execute phpmd
    "phpmd_run": false,

    // Execute the phpmd on file save
    "phpmd_command_on_save": true,

    // It seems python/sublime cannot always find the phpmd application
    // If empty, then use PATH version of phpmd, else use the set value
    "phpmd_executable_path": "",

    // Additional arguments you can specify into the application
    //
    // Example:
    // {
    //     "codesize,unusedcode"
    // }
    "phpmd_additional_args": {
        "codesize,unusedcode,naming": ""
    }
}
</code></pre>

user phpcs.sublime-settings:

<pre><code> {
    /**
      * PHPCS PLUGIN
      */

    // Turn the debug output on/off
    "show_debug":false,

     // Execute the sniffer on file save
    "phpcs_execute_on_save": false,

    // It seems python/sublime cannot always find the phpcs application
    // If empty, then use PATH version of phpcs, else use the set value
    "phpcs_executable_path": "/usr/bin/phpcs",

    /**
     * PHP_CS_FIXER
     */

    // Fix the issues on save
    "php_cs_fixer_on_save": true,

    // Show the quick panel
    "php_cs_fixer_show_quick_panel": true,

    // Path to where you have the php-cs-fixer installed
    "php_cs_fixer_executable_path": "/usr/local/bin/php-cs-fixer",
     // Path to where you have the php-cs-fixer installed
    //"php_cs_fixer_executable_path": "/home/exadra37/Transferências/php-cs-fixer.phar",

    // Additional arguments you can specify into the application
    //
    // Example:
    // {
    //     "--level": "all"
    // }
    // "php_cs_fixer_additional_args": {
    //     "--fixers": "identation,linefeed,trailing_spaces,unused_use,php_closing_tag,short_tag,return,visibility,eof_ending,extra_empty_lines,include,psr0,controls_spaces,elseif"
    // },

    /**
     * PHP Linter
     */
    // It seems python/sublime cannot always find the php application
    // If empty, then use PATH version of php, else use the set value
    "phpcs_php_path": "/usr/bin/phpcs",

    /*
     * PHPMD
     */

    // Execute phpmd
    "phpmd_run": true,

    // It seems python/sublime cannot always find the phpmd application
    // If empty, then use PATH version of phpmd, else use the set value
    "phpmd_executable_path": "/usr/bin/phpmd"
}
</code></pre>

I like very much to use this plugin, but this 3 time i try withou any sucess.

I have a fresh install from ubuntu 12.04.1 and last  sublime text 2 version.

Can anybody point to me what is wrong?

Many thanks

**Comment by kazitanvirahsan** [comment]
In my case phpmd was not working properly because I did not pass the phpmd_additional_args.
