### ISSUE TITLE
Windows 7, Sniffer and CS Fixer not working

### ISSUE THREAD

**Issue by Narretz** [benmatselby/sublime-phpcs#63]
Sorry to bother you again with Windows issues. This is more or less a reminder for myself that it probably won't work next time I'll try.

Win 7 Professional 64-bit SP1
WAMP Server 2.2
PHP 5.3.13
Sublime 2.0.1 / fresh portable
PHPCS: 2013.01.08

```
{
    "show_debug" : true,
    "phpcs_executable_path": "c:/wamp/bin/php/php5.3.13/phpcs.bat",
    "phpcs_additional_args": {
        "--standard": "PSR2",
        "-n": ""
    },
    "phpcs_php_prefix_path": "c:\\wamp\\bin\\php\\php5.3.13\\php.exe",
    "php_cs_fixer_executable_path": "c:\\wamp\\bin\\php\\php5.3.13\\php-cs-fixer.phar",
    "phpcs_linter_run": false
}
```
- Code Sniffer reports 0 errors. Works in console.
- CS Fixer cannot open .phar file (same as console)

Question: Is `"phpcs_php_prefix_path"`` correctly configured? I'll find the docs very vague in this respect without an example.

Another one: In the console, why does the plugin report "Linter found 0 errors", "MessDetector found 0 errors" even if I have them turned off? It's confusing.

**Comment by sudheer82** [comment]
when the following setting is enabled
```
   "php_cs_fixer_additional_args": {
        "--level": "all"
    },
```

fixer is throwing the following error
```
[InvalidArgumentException]       
  The level "all" is not defined. 
```

other than this, the provided setting file works great on ST3 in Win 7
