### ISSUE TITLE
phpcs commands not in palette immediately after sniffer finds errors

### ISSUE THREAD

**Issue by Narretz** [benmatselby/sublime-phpcs#66]
Platform: Win 7, ST 2.0.1 build 2217

Steps to reproduce:
1. Have an error
2. Sniff the file, either on save or from command palette
3. While the quick panel with errors is still open, open the command palette again
4. Search for "sniff"
   => phpcs commands are not found

**Comment by benmatselby** [comment]
Hey @Narretz Thank you for raising this. I'm going to close this ticket down as I cannot replicate this any longer.
