### ISSUE TITLE
Exclude Pattern?

### ISSUE THREAD

**Issue by jerpr** [benmatselby/sublime-phpcs#69]
I have files that end in something like .twig.php for templates that should not be code sniffed. Currently there are only options to whitelist extensions.. would it be possible to exclude these template files somehow?

**Comment by boboldehampsink** [comment]
Is there also a way to exclude directories? I have vendor code that is using tabs instead of spaces and its complaining on every line. I want to exclude the vendor directory from being checked.

**Comment by benmatselby** [comment]
@boboldehampsink Is this when running the sniffer over an entire folder? If so, not at present, but happy to accept a PR

**Comment by boboldehampsink** [comment]
No, this is when I go into the vendor folder and open any (non-compliant) file there. I just want this checker to skip any given exclusions by folder.

**Comment by benmatselby** [comment]
@boboldehampsink Sorry, that isn't something it does at the moment, as that would need more config above the config passed over to phpcs. I guess you are running this on save or something and you are making changes in the vendor dir?

**Comment by boboldehampsink** [comment]
Nahh, its just that I'm looking at files in the vendor dir (never change anything there ;-)) - and every line gets a red dot for not being compliant. It bugs me.

**Comment by benmatselby** [comment]
Unless you execute the plugin or have it configured to run on save I'm not sure how it's producing error reports on the files you mention. Can you paste your config in here please and the console output.
