### ISSUE TITLE
ST2 (Build 2221) not reloading file

### ISSUE THREAD

**Issue by mtibben** [benmatselby/sublime-phpcs#92]
When using `"php_cs_fixer_on_save": true,` php-cs-fixer is running on save however the file is not reloaded in ST2 to reflect the changes that are made. Closing the file and opening it again shows the changes.

**Comment by leonardoalifraco** [comment]
This is happening to me too. The fixer runs, but the editor is not reloading the file, so i can't see the changes until i close and open the file again.

**Comment by leonardoalifraco** [comment]
If i have the config "php_cs_fixer_show_quick_panel": true then it reloads, if it is in false, it doesn't.

**Comment by benmatselby** [comment]
@leonardoalifraco Are you running ST2 or 3. By updating that setting you mention in ST3 it works for me

**Comment by leonardoalifraco** [comment]
I am running ST2.

**Comment by benmatselby** [comment]
OK, I think this is a ST2 only issue. I'm not planning on supporting ST2 as ST3 has been out for a year now. Apologies.
